"""empty message

Revision ID: be15d060096c
Revises: 
Create Date: 2021-08-03 21:09:26.949575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be15d060096c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leakSource',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('roles', sa.String(length=6), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('cdomain', sa.String(length=300), nullable=False),
    sa.Column('site', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdomain'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('site')
    )
    op.create_table('leakCPFCNPJ',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('CPF_CNPJ', sa.String(length=100), nullable=False),
    sa.Column('leak_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['leak_id'], ['leakSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leakEmail',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('leak_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['leak_id'], ['leakSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leakGeneral',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('leaks', sa.String(length=100), nullable=True),
    sa.Column('leak_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['leak_id'], ['leakSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leakWarning',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('warning_type', sa.String(length=6), nullable=False),
    sa.Column('comp_domain', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('leak_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['leak_id'], ['leakSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leakPassword',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=600), nullable=True),
    sa.Column('leak_id', sa.String(length=32), nullable=True),
    sa.Column('email_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['leakEmail.id'], ),
    sa.ForeignKeyConstraint(['leak_id'], ['leakSource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validatedEmails',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('valid_email', sa.Boolean(), nullable=False),
    sa.Column('email_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['leakEmail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validatedEmails')
    op.drop_table('leakPassword')
    op.drop_table('leakWarning')
    op.drop_table('leakGeneral')
    op.drop_table('leakEmail')
    op.drop_table('leakCPFCNPJ')
    op.drop_table('user')
    op.drop_table('leakSource')
    # ### end Alembic commands ###
