"""empty message

Revision ID: edc3cdb19caf
Revises: be15d060096c
Create Date: 2021-09-16 21:33:48.540091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc3cdb19caf'
down_revision = 'be15d060096c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leakCPFCNPJ', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('leakCPFCNPJ', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('leakEmail', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('leakEmail', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('leakGeneral', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('leakGeneral', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('leakPassword', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('leakPassword', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('leakSource', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('leakSource', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('leakWarning', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('leakWarning', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('validatedEmails', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('validatedEmails', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validatedEmails', 'updated')
    op.drop_column('validatedEmails', 'created')
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    op.drop_column('leakWarning', 'updated')
    op.drop_column('leakWarning', 'created')
    op.drop_column('leakSource', 'updated')
    op.drop_column('leakSource', 'created')
    op.drop_column('leakPassword', 'updated')
    op.drop_column('leakPassword', 'created')
    op.drop_column('leakGeneral', 'updated')
    op.drop_column('leakGeneral', 'created')
    op.drop_column('leakEmail', 'updated')
    op.drop_column('leakEmail', 'created')
    op.drop_column('leakCPFCNPJ', 'updated')
    op.drop_column('leakCPFCNPJ', 'created')
    # ### end Alembic commands ###
